Repository ASHISH26940/toogoodto, pull requests merged in 2024-01, with the labels that each got.

#7 Change the favicon
  index.html
Labels: apertre

#11 Fix the cursor effect
  index.html
  script.js
  style.css
Labels: enhancement, apertre

#17 Image overlay feature added
  assests/img/fwdarr.png
  index.html
  script.js
  style.css
Labels: enhancement, apertre

#18 Fix the font family and text structure
  style.css
Labels: apertre, easy

#27 fixed footer bug
  assests/img/brush.svg
  index.html
  style.css
Labels: enhancement, apertre, medium

#31 new pr after updating branch
  index.html
  style.css
Labels: enhancement, apertre, medium

#35 Addition of navbar for mobile device
  index.html
  navbar.js
  style.css
Labels: enhancement, apertre, medium

#38 Add responsive footer
  index.html
  style.css
Labels: enhancement, apertre, medium

#42 #4 Created toggle button
  index.html
  moon-icon.png
  script.js
  style.css
  sun-icon2.png
Labels: enhancement, apertre, medium

#46 issue #33 made dropping animation
  assests/img/Cleanse Nourish Hand Wash Two Go.png
  assests/img/DSC0002_Dexter Kim.png
  assests/img/DSC0032_Dexter Kim.png
  assests/img/DSC0058_Dexter Kim.png
  assests/img/DSC0069_Dexter Kim copy.png
  assests/img/Nourish Soothe Hand Lotion Two G.png
  index.html
  script.js
  style.css
Labels: enhancement, apertre, hard

#51 Update README.md
  README.md
Labels: enhancement, apertre, easy

#52 Make the button responsive
  style.css
Labels: enhancement, apertre, medium

#55 Beautiful Image Hover Effect
  index.html
  script.js
  style.css
Labels: enhancement, apertre, medium

#59 made Navbar look cooler
  index.html
  script.js
  style.css
Labels: enhancement, apertre, hard

#63 page3 responsive
  .vscode/settings.json
  style.css
Labels: enhancement, apertre, medium

#65 Enhanced readme
  README.md
Labels: documentation, enhancement, apertre, easy

#68 fixed some issues
  .vscode/settings.json
  index.html
  style.css
Labels: enhancement, apertre, easy

#71 Footer enhance
  assests/img/brush.mp4
  index.html
  script.js
  style.css
Labels: enhancement, apertre, hard

#73 Enhanced footer
  index.html
Labels: enhancement, apertre, hard

#88 #41 issue solved
  style.css
Labels: enhancement, apertre, hard

#90 Update README.md
  README.md
Labels: documentation, enhancement, apertre, easy
